-- =========================================================
-- MIGRATIE: alle overige websiteteksten toevoegen
-- Voer dit uit in Supabase → SQL Editor → New query → Run.
-- Veilig om meermaals te draaien (bestaande teksten blijven staan).
-- =========================================================
insert into site_texts (key, value) values
  ('nav_home', 'Home'),
  ('nav_muzikanten', 'Muzikanten'),
  ('nav_repertoire', 'Repertoire'),
  ('nav_kalender', 'Kalender'),
  ('nav_media', 'Beluister'),
  ('nav_fotos', 'Foto''s'),
  ('nav_boeking', 'Boeking'),
  ('cta_boeking_btn', 'Naar boekingsinformatie'),
  ('footer_blurb', 'Sfeervolle akoestische muziek voor trouwrecepties, recepties, tuinfeesten en personeelsfeesten.'),
  ('footer_nav_heading', 'Navigatie'),
  ('footer_contact_heading', 'Contact'),
  ('footer_email', 'info@nikitaunbound.be'),
  ('footer_phone', '+32 470 00 00 00'),
  ('footer_city', 'Gent, België'),
  ('social_instagram_url', ''),
  ('social_facebook_url', ''),
  ('footer_copyright', 'Nikita Unbound. Alle rechten voorbehouden.'),
  ('footer_tagline', 'Akoestisch • Intiem • Onbegrensd'),
  ('splash_cta', 'Kom binnen, en ontdek Nikita Unbound.'),
  ('hero_eyebrow', 'Live muziek op maat van uw gelegenheid'),
  ('hero_title', 'Sfeervolle klanken,<br><em>onbegrensd</em> gevoel.'),
  ('hero_lede', 'Nikita Unbound giet tijdloze nummers van de jaren 60 tot vandaag in een intiem, akoestisch jasje. Warme stem, meeslepende percussie — de perfecte soundtrack voor uw trouwreceptie, tuinfeest of bedrijfsevent.'),
  ('hero_btn_boeking', 'Vraag een boeking aan'),
  ('hero_btn_media', 'Beluister ons'),
  ('occasions_eyebrow', 'Voor elke gelegenheid'),
  ('occasions_title', 'De juiste sfeer, elke keer'),
  ('occasions_lead', 'Van een fluisterzacht huwelijksmoment tot een levendige receptie: wij stemmen ons repertoire en onze klank af op uw gelegenheid.'),
  ('occasion1_title', 'Trouwrecepties'),
  ('occasion1_desc', 'Een warme, ingetogen klank tijdens het aperitief en de receptie.'),
  ('occasion2_title', 'Recepties'),
  ('occasion2_desc', 'Achtergrondmuziek met karakter, nooit opdringerig.'),
  ('occasion3_title', 'Tuinfeesten'),
  ('occasion3_desc', 'Akoestisch en flexibel opgesteld, ook buiten onder de bomen.'),
  ('occasion4_title', 'Personeelsfeesten'),
  ('occasion4_desc', 'Een verzorgde noot voor uw bedrijfsevenement.'),
  ('about_eyebrow', 'Over Nikita Unbound'),
  ('about_title', 'Twee muzikanten, één intieme klank'),
  ('about_text', 'Nikita''s warme, frisse stem en Jan''s doorleefde percussie versmelten tot akoestische versies van nummers die u kent en herkent — van jaren 60 klassiekers tot hedendaagse hits. Geen strak podiumshow, wel een oprechte, meeslepende luisterervaring die perfect past bij kleinschalige en persoonlijke gelegenheden.'),
  ('about_btn', 'Maak kennis met de muzikanten'),
  ('home_cta_eyebrow', 'Klaar om te boeken?'),
  ('home_cta_title', 'Laat ons uw feest inkleuren'),
  ('home_cta_lead', 'Bekijk onze beschikbaarheid, ontdek ons repertoire of stuur meteen een aanvraag.'),
  ('home_cta_btn1', 'Bekijk kalender'),
  ('home_cta_btn2', 'Boekingsinformatie'),
  ('muz_hero_eyebrow', 'De muzikanten'),
  ('muz_hero_title', 'Twee stemmen, één ritme'),
  ('muz_hero_lead', 'Achter Nikita Unbound schuilen twee muzikanten met een gedeelde liefde voor tijdloze songs — elk met hun eigen achtergrond en hun eigen instrument.'),
  ('muz_trio_note', 'Samen bouwden Nikita en Jan een repertoire uit dat moeiteloos schakelt tussen decennia en stijlen — steeds met hetzelfde uitgangspunt: een sfeervolle, intieme uitvoering die past bij het moment.'),
  ('muz_cta_eyebrow', 'Onze klank'),
  ('muz_cta_title', 'Akoestisch, ingetogen, tijdloos'),
  ('muz_cta_lead', 'Benieuwd hoe dat precies klinkt? Beluister opnames en bekijk live-beelden, of ontdek het volledige repertoire.'),
  ('muz_cta_btn1', 'Beluister ons'),
  ('muz_cta_btn2', 'Bekijk repertoire'),
  ('kal_hero_eyebrow', 'Agenda'),
  ('kal_hero_title', 'Aankomende optredens'),
  ('kal_hero_lead', 'Een overzicht van waar en wanneer u Nikita Unbound kan horen spelen. Sommige optredens zijn besloten feesten, andere zijn vrij toegankelijk.'),
  ('kal_cta_eyebrow', 'Uw datum nog niet gevonden?'),
  ('kal_cta_title', 'Vraag uw eigen optreden aan'),
  ('kal_cta_lead', 'Wij plannen graag mee met uw agenda. Stuur ons uw gewenste datum door via het boekingsformulier.'),
  ('rep_hero_eyebrow', 'Repertoire'),
  ('rep_hero_title', 'Nummers van jaren 60 tot vandaag'),
  ('rep_hero_lead', 'Blader door ons repertoire, filter op decennium of zoek een titel. Bent u al geboekt? Vink dan hieronder uw favoriete nummers aan.'),
  ('rep_selection_label', 'nummer(s) geselecteerd'),
  ('rep_selection_btn', 'Selectie doorsturen'),
  ('rep_form_eyebrow', 'Al geboekt?'),
  ('rep_form_title', 'Stuur uw nummerkeuze door'),
  ('rep_form_lead', 'Selecteer hierboven uw favoriete nummers uit het repertoire en vul onderstaand formulier in. Staat een nummer er niet bij? Vraag het gerust aan — we bekijken of we het kunnen instuderen tegen uw feest.'),
  ('rep_submit_btn', 'Nummerkeuze doorsturen'),
  ('rep_form_note', 'Nog geen boeking? Regel dit eerst via de <a href="boeking.html" style="text-decoration:underline;">boekingspagina</a>.'),
  ('rep_success_msg', 'Bedankt! Uw nummerkeuze is genoteerd, we nemen dit mee in de voorbereiding van uw feest.'),
  ('boek_hero_eyebrow', 'Boeking'),
  ('boek_hero_title', 'Boek Nikita Unbound voor uw feest'),
  ('boek_hero_lead', 'Van een eerste vraag tot de dag van uw evenement — dit is hoe een boeking bij ons verloopt, en alle info die u vooraf wil weten.'),
  ('info_card1_num', '2'),
  ('info_card1_title', 'Bezetting'),
  ('info_card1_desc', 'Zang en percussie, akoestisch en intiem — ideaal voor kleinere en middelgrote ruimtes, binnen of buiten.'),
  ('info_card2_num', '±45'''),
  ('info_card2_title', 'Speelduur per set'),
  ('info_card2_desc', 'Sets op maat van uw programma, met pauzes voor speeches of ander vermaak. In overleg samen te stellen.'),
  ('info_card3_num', '±60'''),
  ('info_card3_title', 'Opbouw & soundcheck'),
  ('info_card3_desc', 'Wij komen ruim op tijd voor een discrete opbouw en soundcheck, afgestemd op de locatie.'),
  ('steps_eyebrow', 'Hoe verloopt een boeking'),
  ('steps_title', 'In vier stappen naar uw optreden'),
  ('step1_title', 'Aanvraag versturen'),
  ('step1_desc', 'Vul het formulier hieronder in met de datum, locatie en aard van uw evenement.'),
  ('step2_title', 'Persoonlijk contact'),
  ('step2_desc', 'Wij nemen binnen enkele dagen contact op om details en wensen te bespreken.'),
  ('step3_title', 'Bevestiging & nummerkeuze'),
  ('step3_desc', 'Na bevestiging kan u via de repertoirepagina uw favoriete nummers selecteren of een verzoeknummer aanvragen.'),
  ('step4_title', 'Wij komen spelen'),
  ('step4_desc', 'Op de dag zelf zorgen wij voor een discrete opbouw en een sfeervol optreden op maat.'),
  ('boek_form_eyebrow', 'Informatie aanvragen'),
  ('boek_form_title', 'Vertel ons over uw feest'),
  ('booking_lede', 'Vul onderstaand formulier in en we bezorgen u vrijblijvend meer informatie of een offerte op maat.'),
  ('boek_submit_btn', 'Verstuur aanvraag'),
  ('boek_form_note', 'We behandelen uw gegevens vertrouwelijk en gebruiken ze uitsluitend om uw aanvraag te beantwoorden.'),
  ('boek_success_msg', 'Bedankt voor uw aanvraag! We nemen binnenkort contact met u op.'),
  ('media_hero_eyebrow', 'Beeld & geluid'),
  ('media_hero_title', 'Beluister en bekijk Nikita Unbound'),
  ('media_hero_lead', 'Een greep uit onze live-registraties en studio-opnames, zodat u perfect weet wat u kan verwachten op uw feest.'),
  ('videos_eyebrow', 'Video''s'),
  ('videos_title', 'Live in beeld'),
  ('video1_title', 'Live optreden — receptie'),
  ('video1_desc', 'Sfeerbeelden van een recente receptie.'),
  ('video2_title', 'Akoestische sessie'),
  ('video2_desc', 'Intieme studio-opname van ons repertoire.'),
  ('videos_placeholder_note', 'Dit zijn placeholders ter illustratie van de lay-out. Vervang elk placeholdervlak in media.html door een echte YouTube- of Vimeo-embed (<iframe>) van uw eigen beeldmateriaal.'),
  ('audio_eyebrow', 'Opnames'),
  ('audio_title', 'Beluister onze nummers'),
  ('audio1_title', 'Fly Me to the Moon (akoestische versie)'),
  ('audio1_meta', 'Studio-opname'),
  ('audio2_title', 'Songbird'),
  ('audio2_meta', 'Live registratie'),
  ('audio3_title', 'Ho Hey'),
  ('audio3_meta', 'Studio-opname'),
  ('audio_placeholder_note', 'Voeg uw eigen MP3-bestanden toe in de map assets/audio/ en verwijs ernaar in media.html om deze spelers te laten afspelen.'),
  ('media_cta_eyebrow', 'Overtuigd?'),
  ('media_cta_title', 'Boek Nikita Unbound voor uw feest'),
  ('fotos_hero_eyebrow', 'Foto''s'),
  ('fotos_hero_title', 'Momenten in beeld'),
  ('fotos_hero_lead', 'Een sfeerbeeld van Nikita Unbound op locatie en achter de schermen.'),
  ('fotos_placeholder_note', 'De vakken met tekst zijn placeholders. Vervang deze in fotos.html door eigen foto''s: voeg de bestanden toe aan assets/ en verwijs ernaar met een <img>-tag, zoals bij de eerste foto.'),
  ('fotos_cta_eyebrow', 'Zelf meemaken?'),
  ('fotos_cta_title', 'Boek Nikita Unbound voor uw feest')
on conflict (key) do nothing;
